
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network
  
  api-proxy:
    image: node:20-alpine
    volumes:
      - ./api-proxy:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - MERCEDES_API_URL=http://mercedes:8000
    restart: unless-stopped

networks:
  app-network:
    external: true  # Connect to the same network used by Mercedes
