
version: '3.8'

services:
  mercedes-fe:
    container_name: mercedes-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true  # Connect to the same network used by Mercedes

