
version: '3.8'

services:
  mercedes-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.mercedes-fe.rule=Host(`dev.ai-assistant.corp.aleido.se`)
      - traefik.http.routers.mercedes-fe.entrypoints=websecure
      - traefik.http.routers.mercedes-fe.tls=true
      - traefik.http.services.mercedes-fe.loadbalancer.server.port=8080
    networks:
      - ollama
      - traefik
    restart: unless-stopped
  
networks:
  ollama:
    external: true
  traefik:
    external: true
